pkgbot:
  - repo: adsy-testing
    download-delay: 5
    branches:
      - master
      - testing
    packages:
      debian:
        bullseye:
          - dist/python-gitlab-pkgbot_*_all.deb
        bookworm:
          - dist/python-gitlab-pkgbot_*_all.deb
        trixie:
          - dist/python-gitlab-pkgbot_*_all.deb
